### PR TITLE
[WIP] Removed liip functional bundle and added support for Symfony 4

### PR DESCRIPTION
**Pull request by dragosprotung**
This is the first try to get rid of liip functional bundle and support Symfony 4.

The code still works with Symfony 3, but the API is a changed.

This is according to #10

### CODE REVIEW

**Comment by cezarystepkowski** [comment]
@dragosprotung  `0.x` and `1.x` branching is a good idea .👍 

Thanks for taking time to write README.md as well! :)

I'll add you as a collaborator to the repository, I think that would simplify the process as anyway you're working intensively on it right now.

If you'll need any help feel free to contact me.

**Comment by cezarystepkowski** [comment]
Thanks for the pull request @dragosprotung!

I tested it on Symfony 3.4 and almost everything works fine! 

There is just one thing: fixtures loader now uses the same container as the one in tests. It might lead to some problems.

For example let's say that you have a fixture loader that loads an entity that has a doctrine event listener attached (for example postPersist). Because of that the listener is instantiated when loading the fixtures. Later on you want to mock the service that is injected into that event listener by using the `mockContainerService` method from `KernelTestCase` but because the event listener was already instantiated with the real service your mocked method will not be called and you'll end up with method from real service being called.

I managed to overcome this problem by extending the WebTestCase and overriding the setUp method to call bootKernel once again so that later on I have a "fresh" container. It looks like this:
```
    public function setUp() : void
    {
        parent::setUp();

        self::bootKernel();
    }
```

Another solution could be to boot different kernel and get the container from it just for the fixtures loader. This way container used in fixtures is different that the one used in tests.

Any idea how to put it in the library? Did you have similar issues on Symfony 4?

BTW tests run significantly faster with this version 🎉

**Comment by dragosprotung** [comment]
In Symfony 4 the compiler pass `PublicContainerServicesForTests` should be used in test environment. This will create a special version of the container that will solve this kind of problems.

I use this new version on a Symfony 3.4 project as well and there I do not have this issue, but maybe I do not have such a complex scenario.

I think that temporarily the solution would be to boot the kernel again only when needed until the project gets upgraded to Symfony 4

**Comment by cezarystepkowski** [comment]
Booting the kernel again has no negative impact so I will leave it as it is and follow your suggested solution.
All looks good, thanks @dragosprotung !

**Pull request merged**
