### PR TITLE
Use phpunit constraints for assertions

### PR DESCRIPTION
**Pull request by cezarystepkowski**

### CODE REVIEW

**Comment by dragosprotung** [comment]
Very nice work !

Is there any reason to keep BC with PHPUnit < 8 ?

**Comment by cezarystepkowski** [comment]
No particular reason, I just wanted to have wider compatibility because PHPUnit 7.5 is still actively maintained. On the other hand, bumping the requirements to PHPUnit >= 8 will make code cleaner and for PHPUnit 7.5 FunctionalTestBundle 0.x can be used. What do you think?

**Comment by dragosprotung** [comment]
I am a bit more aggressive with support for older versions. By the time version 1.0 will be release there will only be a few more months of support (if any) for PHPUnit < 8.

And like you said, for PHPUnit < 8 an older version of this package can be used.

I am more in favor of dropping support for version < 8.
Is there anything else that needs to be done for compatibility ? If not, then we could keep it for

**Comment by cezarystepkowski** [comment]
At the moment library is fully compatible with version 7.5 of PHPUnit.

**Comment by dragosprotung** [comment]
In this case I see no reason to keep it.

**Comment by cezarystepkowski** [comment]
Let's drop the support for PHPUnit < 8 then. I'll open a new ticket for it and do a separate PR.

**Comment by dragosprotung** [comment]
I meant that i see no reason to remove support for PHPUnit < 8 if it's already there :)

**Comment by cezarystepkowski** [comment]
Haha, but still you convinced me to remove the support :)

**Pull request merged**
