### PR TITLE
Apply Doctrine CS

### PR DESCRIPTION
**Pull request by dragosprotung**

### CODE REVIEW

**Comment by dragosprotung** [comment]
Some 
```
/**
  * {@inheritdoc}
  */
```
can be removed, but will require BC break

**Comment by dragosprotung** [comment]
ping @cezarystepkowski

**Comment by cezarystepkowski** [comment]
@dragosprotung I am fine with BC break, we'll release version 0.8 anyway. 
Can you remove the `{@inheritdoc}` annotations where possible and explain what BC it will break?

**Comment by dragosprotung** [comment]
If we remove the `{@inheritdoc}` the CS will force us to add the `void` return type. That means any method overwrite will require to have the method signatures updated.

I can remove the doc comment in a new PR and this one can be merged (if nothing else to add / change)

**Comment by dragosprotung** [comment]
@cezarystepkowski can you share what is planned for 0.8 ? Is it currently in development ? 

I would like to bring Symfony 4 compatibility and this will be a big change.

**Comment by dragosprotung** [comment]
I was thinking of removing the dependency since there is very little used from it considering the reason behind the project. I will create a new RFC issue for this in the next day

**Pull request merged**
